# Generated by Django 5.0.1 on 2024-03-04 18:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Receita', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ENTRADAS', 'Entradas'), ('PETISCOS', 'Petiscos'), ('PRATOS', 'Pratos'), ('DOCES', 'Doces')], default='', max_length=10)),
                ('modo_de_preparo', models.TextField()),
                ('publicada', models.BooleanField(default=True)),
                ('data_receita', models.DateTimeField(default=datetime.datetime.now)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=1, max_digits=4)),
                ('unidade', models.CharField(choices=[('g', 'gramas'), ('kg', 'quilos'), ('ml', 'mililitros'), ('l', 'litros'), ('colher(es) chá', 'colheres chá'), ('colher(es) sopa', 'colheres sopa'), ('un', 'unidades'), ('xícara(s)', 'xícaras'), ('pitada', 'pitada'), ('lata(s)', 'lata'), ('à gosto', 'à gosto')], max_length=15)),
                ('categoria', models.CharField(blank=True, choices=[('massa', 'Massa'), ('recheio', 'Recheio'), ('cobertura', 'Cobertura')], default='', max_length=20)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receita.ingrediente')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receita.receita')),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='ingredientes',
            field=models.ManyToManyField(through='receita.ReceitaIngrediente', to='receita.ingrediente'),
        ),
    ]
