# Generated by Django 5.0.1 on 2024-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='tipo',
            field=models.CharField(choices=[('PETISCOS', 'Petiscos'), ('DOCES', 'Doces'), ('PRATOS', 'Pratos'), ('ENTRADAS', 'Entradas')], default='', max_length=10),
        ),
    ]
