# Generated by Django 5.0.1 on 2024-03-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
