# Generated by Django 5.0.1 on 2024-03-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_alter_receita_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitaingrediente',
            name='categoria',
            field=models.CharField(blank=True, choices=[('massa', 'Massa'), ('recheio', 'Recheio'), ('cobertura', 'Cobertura')], default='', max_length=20),
        ),
    ]
