# Generated by Django 5.0.1 on 2024-03-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compras', '0001_initial'),
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdelista',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='itens_de_lista', to='receita.receitaingrediente'),
        ),
    ]
