# Generated by Django 5.0.1 on 2024-03-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compras', '0003_remove_itemdelista_ingredientes_itemdelista_lista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadecompras',
            name='itens',
            field=models.ManyToManyField(blank=True, default='', related_name='listas_de_compras', to='lista_compras.itemdelista'),
        ),
    ]
