# Generated by Django 5.0.1 on 2024-03-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compras', '0004_alter_listadecompras_itens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadecompras',
            name='itens',
        ),
        migrations.AddField(
            model_name='itemdelista',
            name='medida',
            field=models.CharField(choices=[('g', 'gramas'), ('kg', 'quilos'), ('l', 'litros'), ('un', 'unidades'), ('lata(s)', 'lata'), ('dz', 'dúzias'), ('pc', 'pacotes'), ('cx', 'caixas')], default='', max_length=20),
        ),
    ]
