# Generated by Django 5.0.1 on 2024-03-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compras', '0005_remove_listadecompras_itens_itemdelista_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdelista',
            name='medida',
            field=models.CharField(choices=[('g', 'gramas'), ('kg', 'quilos'), ('l', 'litros'), ('un', 'unidades'), ('lata(s)', 'lata'), ('dz', 'dúzias'), ('pc', 'pacotes'), ('cx', 'caixas')], default='un', max_length=20),
        ),
    ]
