# Generated by Django 5.0.1 on 2024-03-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compras', '0006_alter_itemdelista_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdelista',
            name='medida',
            field=models.CharField(choices=[('g', 'gramas'), ('kg', 'quilos'), ('l', 'litros'), ('un', 'unidades'), ('lata(s)', 'latas'), ('dz', 'dúzias'), ('pc', 'pacotes'), ('cx', 'caixas')], default='un', max_length=20),
        ),
    ]
